flake_head = """{
  description = "nvim plugins bundled in a single directory using linkFarm";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = {
    self,
    nixpkgs,
  }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};

    customPlugins = {
      """

flake_neck = r"""
    };

    customList =
      pkgs.lib.attrsets.mapAttrsToList (_name: package: {
        name = _name;
        path = package;
      })
      customPlugins;

    nixpkgsList = with pkgs.vimPlugins; [
      """

flake_foot = r"""
    ];

    fullList = customList ++ nixpkgsList;

    pluginMeta =
      map (p: {
        name = p.name;
        path = "${p.path}";
        rev = p.path.src.rev or "unknown";
        version = p.path.version or "unknown";
      })
      fullList;

    jsonFile = builtins.toJSON (
      builtins.listToAttrs (map (m: {
          name = m.name;
          value = {
            inherit (m) name path rev version;
          };
        })
        pluginMeta)
    );

    luaFile =
      ''
        -- Auto-generated by Nix, do not edit.
        return {
      ''
      + pkgs.lib.concatMapStrings (m: ''
        ["${m.name}"] = {
          path    = "${m.path}",
          rev     = "${m.rev}",
          version = "${m.version}",
        },
      '')
      pluginMeta
      + ''
        }
      '';

    nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
      cp -r ${pkgs.linkFarm "nvim-plugins" fullList} $out
      chmod -R u+w $out

      # Add meta files
      mkdir -p $out/meta

      cat > $out/meta/plugin_paths.lua << 'EOF'
      ${luaFile}
      EOF

      ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

      cat > $out/meta/plugin_paths.json << 'EOF'
      ${jsonFile}
      EOF

      ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json > $out/meta/tmp.json
      mv $out/meta/tmp.json $out/meta/plugin_paths.json
    '';
  in {
    packages.${system} = {
      inherit nvimPlugins;
      default = nvimPlugins;
      json = jsonFile;
      lua = luaFile;
    };
  };
}
"""

expression_head = """# Created by nvimtool.

{ pkgs }: {
  customPlugins = {
    """

expression_neck = r"""
  };

  customList =
    pkgs.lib.attrsets.mapAttrsToList (_name: package: {
      name = _name;
      path = package;
    })
    customPlugins;

  nixpkgsList = with pkgs.vimPlugins; [
      """

expression_foot = r"""
  ];

  fullList = customList ++ nixpkgsList;

  pluginMeta =
    map (p: {
      name = p.name;
      path = "${p.path}";
      rev = p.path.src.rev or "unknown";
      version = p.path.version or "unknown";
    })
    fullList;

  jsonFile = builtins.toJSON (
    builtins.listToAttrs (map (m: {
      name = m.name;
      value = {
        inherit (m) name path rev version;
      };
    })
    pluginMeta)
  );

  luaFile =
    ''
    -- Auto-generated by Nix, do not edit.
    return {
    ''
    + pkgs.lib.concatMapStrings (m: ''
        ["${m.name}"] = {
          path    = "${m.path}",
          rev     = "${m.rev}",
          version = "${m.version}",
        },
    '')
    pluginMeta
    + ''
    }
    '';

  nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
    cp -r ${pkgs.linkFarm "nvim-plugins" fullList} $out
    chmod -R u+w $out

    # Add meta files
    mkdir -p $out/meta

    cat > $out/meta/plugin_paths.lua << 'EOF'
    ${luaFile}
    EOF

    ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

    cat > $out/meta/plugin_paths.json << 'EOF'
    ${jsonFile}
    EOF

    ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json > $out/meta/tmp.json
    mv $out/meta/tmp.json $out/meta/plugin_paths.json
  '';
}
"""
