from .datamodels import PluginSpecs, SinglePluginSpec, Source

lbrace = "{"
rbrace = "}"
indent_size = 2
level0 = ""
level1 = " " * 1 * indent_size
level2 = " " * 2 * indent_size
level3 = " " * 3 * indent_size
level4 = " " * 4 * indent_size


plugin_expr_template = """{name} = pkgs.vimUtils.buildVimPlugin {lbrace}
        pname = "{nix_name}";
        version = "{version}";
        src = pkgs.fetchgit {lbrace}
          url = "{url}";
          rev = "{rev}";
          hash = "{nix_hash}";
        {rbrace};
        doCheck = false;
        meta = {lbrace}
          homepage = "{url}";
          description = "";
        {rbrace};
      {rbrace};"""


plugin_expr_template_gh = """{name} = pkgs.vimUtils.buildVimPlugin {lbrace}
        pname = "{nix_name}";
        version = "{version}";
        src = pkgs.fetchFromGitHub {lbrace}
          owner = "{owner}";
          repo = "{repo}";
          rev = "{rev}";
          hash = "{nix_hash}";
        {rbrace};
        doCheck = false;
        meta = {lbrace}
          homepage = "{url}";
          description = "";
        {rbrace};
      {rbrace};"""


def make_expression(ps: SinglePluginSpec) -> str:
    try:
        source = Source(ps.source)
        base = {
            Source.GH: "https://github.com",
            Source.GL: "https://gitlab.com",
            Source.CB: "https://codeberg.org",
        }.get(source, "")
        if ps.source == "gh":
            template = plugin_expr_template_gh
            owner, repo = ps.id.split("/")
        else:
            template = plugin_expr_template
            owner, repo = "", ""

        ret = template.format(
            name=ps.name,
            nix_name=ps.nixName,
            version=ps.lastCommit or "1970-01-01",
            url="/".join((base, ps.id)).strip("/"),
            rev=ps.rev,
            nix_hash=ps.hash,
            lbrace="{",
            rbrace="}",
            owner=owner,
            repo=repo,
        )
        # print(ret)
        return ret
    except Exception as e:
        print(e)
        print(ps)
        raise e


def make_name(ps: SinglePluginSpec) -> str:
    attrset = ps.attrset
    nix_name = ps.nixName
    return f"{attrset}.{nix_name}"


def make_nixpkgs_set(ps: SinglePluginSpec) -> str:
    nix_name = (
        ps.nixName if ps.attrset == "pkgs.vimPlugins" else f"{ps.attrset}.{ps.nixName}"
    )
    return f'{lbrace}\n{level4}name = "{ps.name}";\n{level4}path = {nix_name};\n{level3}{rbrace}'


head = """{
  description = "nvim plugins bundled in a single directory using linkFarm";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = {
    self,
    nixpkgs,
  }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};

    customPlugins = {
      """

neck = r"""
    };

    customList =
      pkgs.lib.attrsets.mapAttrsToList (_name: package: {
        name = _name;
        path = package;
      })
      customPlugins;

    nixpkgsList = with pkgs.vimPlugins; [
      """

foot = r"""
    ];

    fullList = customList ++ nixpkgsList;

    pluginMeta =
      map (p: {
        name = p.name;
        path = "${p.path}";
        rev = p.path.src.rev or "unknown";
        version = p.path.version or "unknown";
      })
      fullList;

    jsonFile = builtins.toJSON (
      builtins.listToAttrs (map (m: {
          name = m.name;
          value = {
            inherit (m) name path rev version;
          };
        })
        pluginMeta)
    );

    luaFile =
      ''
        -- Auto-generated by Nix, do not edit.
        return {
      ''
      + pkgs.lib.concatMapStrings (m: ''
        ["${m.name}"] = {
          path    = "${m.path}",
          rev     = "${m.rev}",
          version = "${m.version}",
        },
      '')
      pluginMeta
      + ''
        }
      '';

    nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
      cp -r ${pkgs.linkFarm "nvim-plugins" fullList} $out
      chmod -R u+w $out

      # Add meta files
      mkdir -p $out/meta

      cat > $out/meta/plugin_paths.lua << 'EOF'
      ${luaFile}
      EOF

      ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

      cat > $out/meta/plugin_paths.json << 'EOF'
      ${jsonFile}
      EOF

      ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json > $out/meta/tmp.json
      mv $out/meta/tmp.json $out/meta/plugin_paths.json
    '';
  in {
    packages.${system} = {
      inherit nvimPlugins;
      default = nvimPlugins;
      json = jsonFile;
      lua = luaFile;
    };
  };
}
"""


def build_flake_source(nix_data: PluginSpecs) -> str:
    custom_data = [d for d in nix_data if d.attrset.startswith("custom")]
    nixpkgs_data = [d for d in nix_data if d.attrset.startswith("pkgs")]
    other_data = [
        d for d in nix_data if (d not in custom_data) and (d not in nixpkgs_data)
    ]
    if other_data:
        raise ValueError
    custom = "\n      ".join(map(make_expression, custom_data))
    nixpkgs_list = "\n      ".join(map(make_nixpkgs_set, nixpkgs_data))
    return "".join((head, custom, neck, nixpkgs_list, foot))
