from pathlib import Path
from typing import cast

from adiumentum import read_json

from .datamodels import Source

lbrace = "{"
rbrace = "}"
indent_size = 2
level0 = ""
level1 = " " * 1 * indent_size
level2 = " " * 2 * indent_size
level3 = " " * 3 * indent_size
level4 = " " * 4 * indent_size

nn = Path.home() / ("repos/nvim-config/testing/declarations/nix-info.json")
result = Path.home() / ("repos/nvim-config/testing/snapshots/nvim-plugins.nix")
flake = Path.home() / ("repos/nvim-config/testing/snapshots/flake.nix")

plugin_expr_template = """{name} = pkgs.vimUtils.buildVimPlugin {lbrace}
        pname = "{nix_name}";
        version = "{version}";
        src = pkgs.fetchgit {lbrace}
          url = "{url}";
          rev = "{rev}";
          hash = "{nix_hash}";
        {rbrace};
        doCheck = false;
        meta = {lbrace}
          homepage = "{url}";
          description = "";
        {rbrace};
      {rbrace};"""


plugin_expr_template_gh = """{name} = pkgs.vimUtils.buildVimPlugin {lbrace}
        pname = "{nix_name}";
        version = "{version}";
        src = pkgs.fetchFromGitHub {lbrace}
          owner = "{owner}";
          repo = "{repo}";
          rev = "{rev}";
          hash = "{nix_hash}";
        {rbrace};
        doCheck = false;
        meta = {lbrace}
          homepage = "{url}";
          description = "";
        {rbrace};
      {rbrace};"""


def make_expression(d: dict) -> str:
    try:
        source = Source(d["source"])
        base = {
            Source.GH: "https://github.com",
            Source.GL: "https://gitlab.com",
            Source.CB: "https://codeberg.org",
        }.get(source, "")
        if d["source"] == "gh":
            template = plugin_expr_template_gh
            owner, repo = d["id"].split("/")
        else:
            template = plugin_expr_template
            owner, repo = "", ""

        ret = template.format(
            name=d["name"],
            nix_name=d["nixName"],
            version=d.get("last_commit", "1970-01-01"),
            url="/".join((base, d["id"])).strip("/"),
            rev=d["rev"],
            nix_hash=d["hash"],
            lbrace="{",
            rbrace="}",
            owner=owner,
            repo=repo,
        )
        # print(ret)
        return ret
    except Exception as e:
        print(e)
        print(d)
        raise e


def make_name(d: dict) -> str:
    attrset = d["attrset"]
    nix_name = d["nixName"]
    return f"{attrset}.{nix_name}"


def make_nixpkgs_set(d: dict) -> str:
    nix_name = d["nixName"] if d["attrset"] == "pkgs.vimPlugins" else f"{d['attrset']}.{d['nixName']}"
    return f'{lbrace}\n{level4}name = "{d["name"]}";\n{level4}path = {nix_name};\n{level3}{rbrace}'


nix_data = cast(list[dict], read_json(nn))
custom_data = [d for d in nix_data if d.get("attrset", "").startswith("custom")]
nixpkgs_data = [d for d in nix_data if d.get("attrset", "").startswith("pkgs")]
other_data = [d for d in nix_data if (d not in custom_data) and (d not in nixpkgs_data)]
print(other_data)
custom = "\n      ".join(map(make_expression, custom_data))
nixpkgs_list = "\n      ".join(map(make_nixpkgs_set, nixpkgs_data))
# file_contents = (
#     "{pkgs, lib}:\nlet custom = {\n    "
#     f'{custom}'
#     "\n}; in {\n"
#     "    # config to go here\n}"
# )

# result.write_text(file_contents)

flake_nix = (
    """{
  description = "nvim plugins bundled in a single directory using linkFarm";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = {
    self,
    nixpkgs,
  }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};

    customPlugins = {
      """
    + custom
    + r"""
    };

    customList =
      pkgs.lib.attrsets.mapAttrsToList (_name: package: {
        name = _name;
        path = package;
      })
      customPlugins;

    nixpkgsList = with pkgs.vimPlugins; [
      """
    + nixpkgs_list
    + r"""
    ];

    fullList = customList ++ nixpkgsList;

    pluginMeta =
      map (p: {
        name = p.name;
        path = "${p.path}";
        rev = p.path.src.rev or "unknown";
        version = p.path.version or "unknown";
      })
      fullList;

    jsonFile = builtins.toJSON (
      builtins.listToAttrs (map (m: {
          name = m.name;
          value = {
            inherit (m) name path rev version;
          };
        })
        pluginMeta)
    );

    luaFile =
      ''
        -- Auto-generated by Nix, do not edit.
        return {
      ''
      + pkgs.lib.concatMapStrings (m: ''
        ["${m.name}"] = {
          path    = "${m.path}",
          rev     = "${m.rev}",
          version = "${m.version}",
        },
      '')
      pluginMeta
      + ''
        }
      '';

    nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
      cp -r ${pkgs.linkFarm "nvim-plugins" fullList} $out
      chmod -R u+w $out

      # Add meta files
      mkdir -p $out/meta

      cat > $out/meta/plugin_paths.lua << 'EOF'
      ${luaFile}
      EOF

      ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

      cat > $out/meta/plugin_paths.json << 'EOF'
      ${jsonFile}
      EOF

      ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json > $out/meta/tmp.json
      mv $out/meta/tmp.json $out/meta/plugin_paths.json
    '';
  in {
    packages.${system} = {
      inherit nvimPlugins;
      default = nvimPlugins;
      json = jsonFile;
      lua = luaFile;
    };
  };
}
"""
)

flake.write_text(
    flake_nix,
)

# tmp: dict = cast(dict, Utils.read_json(Path("/home/isaac/repos/nvim-config/testing/tmp.json")))

# def fetch_hashes(d: dict) -> dict:
#     if d["source"] != "gh":
#         return d
#     if d["hash"]:
#         return d
#     try:
#         if d["id"] in tmp:
#             tmp_info = tmp[d["id"]]
#             return d | {
#                 "rev": tmp_info["src"]["rev"],
#                 "hash": tmp_info["src"]["hash"],
#                 "last_commit": tmp_info["meta"].get("commitDate", ""),
#             }
#         command = ["nix-prefetch-github", *d["id"].split("/"), "--json", "--meta"]
#         print('"' + d["id"] + '"')
#         result = (Utils.capture(command))
#         print(result)
#         result = json.loads(result)
#         return d | {
#             "rev": result["src"]["rev"],
#             "hash": result["src"]["hash"],
#             "last_commit": result["meta"].get("commitDate", ""),
#         }
#     except Exception as e:
#         print(e)
#         return d


# nix_data = list(map(fetch_hashes, nix_data))
# Utils.write_json(nix_data, nn)

#  nix run nixpkgs#nix-prefetch-github -- Sharonex edit-list.nvim --json --meta --rev '01e5a827684140ccd20ec249e74da91115dc8c39'
#  nix-prefetch-github-directory --directory edit-list.nvim --json --meta
#  nix-prefetch-git https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim
#
# nix run nixpkgs#nix-prefetch-github -- Sharonex edit-list.nvim --nix
# nix run nixpkgs#nix-prefetch-git -- --url https://codeberg.org/hernandez/dotdot.nvim
